

// import type { Metadata } from "next";
// import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// import { cookies } from "next/headers";
// import { Navbar } from "@/components/common/navbar1";
// import { AuthProvider } from "@/context/AuthContext";
// import { Toaster } from "@/components/ui/sonner";

// const jetbrainsMono = JetBrains_Mono({ 
//   subsets: ['latin'], 
//   variable: '--font-mono' 
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   // Read theme from cookies on the server
//   const cookieStore = await cookies();
//   const theme = cookieStore.get("theme")?.value || "dark";

//   return (
//     <html
//       lang="en"
//       className={cn(theme, "h-full antialiased")} 
//       style={{ colorScheme: theme }} // Tells browser scrollbars/UI to match
//     >
//       <body className={cn(geistSans.className, "min-h-full flex flex-col px-4 md:px-6 lg:px-10")}>
//         <AuthProvider>
          
//           <Navbar className="mb-6" />
//           {children}
//           <Toaster position="top-center" richColors />
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
     

import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { cookies } from "next/headers";
import { Navbar } from "@/components/common/navbar1";
import { Footer } from "@/components/common/footer";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/sonner";
import LayoutWrapper from "@/components/common/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VibeCode Media",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || "dark";
  

  return (
    <html
      lang="en"
      className={cn(theme, "h-full antialiased")} 
      style={{ colorScheme: theme }}
    >
      <body className={cn(geistSans.className, "min-h-full flex flex-col")}>
        <AuthProvider>
          {/* Navbar wrapper to ensure it stays consistent */}
          {/* <main className="flex-1 px-4 md:px-6 lg:px-10 mb-10">
            {children}
          </main> */}
          <Navbar className="" />
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
          <Toaster position="top-center" richColors />
        </AuthProvider>
      </body>
    </html>
  );
}